import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import QueryClientProviderWrapper from "./query-client-provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es">

      <body
        className={`antialiased`}
      >
        <QueryClientProviderWrapper>
          <main>
            {children}
          </main>
        </QueryClientProviderWrapper>
      </body>
    </html>
  );
}
