version: "3.8"
services:
  mongo:
    image: mongo:7
    ports: ["27017:27017"]
    environment:
      MONGO_INITDB_DATABASE: realestate_db
    volumes:
      - mongo_data:/data/db
  mongo-express:
    image: mongo-express
    ports: ["8081:8081"]
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017
volumes:
  mongo_data:
